CREATE DATABASE IF NOT EXISTS cms
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS cms_test
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON cms.* TO 'cms_user'@'%';
GRANT ALL PRIVILEGES ON cms_test.* TO 'cms_user'@'%';

FLUSH PRIVILEGES;